.PHONY: clean All

All:
	@echo "----------Building project:[ UICS - Debug ]----------"
	@"$(MAKE)" -f  "UICS.mk"
clean:
	@echo "----------Cleaning project:[ UICS - Debug ]----------"
	@"$(MAKE)" -f  "UICS.mk" clean
