.TH "msgHandler" 3 "Wed Oct 20 2021" "Version 1.0" "UICS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msgHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetlPath\fP (std::string path)"
.br
.ti -1c
.RI "void \fBsetllevel\fP (int level)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file msghandler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UICS from the source code\&.
