.TH "cmdList" 3 "Wed Oct 20 2021" "Version 1.0" "UICS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcmdList\fP (std::string configPath='')"
.br
.ti -1c
.RI "void \fBprintAllCMD\fP ()"
.br
.ti -1c
.RI "std::string \fBgetCMDlist\fP ()"
.br
.ti -1c
.RI "std::string \fBgetcmdinfo\fP (std::string cmdname)"
.br
.ti -1c
.RI "void \fBprintCMD\fP (std::string name)"
.br
.ti -1c
.RI "\fBcmd\fP \fBoperator[]\fP (std::string str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file uics_cmds\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UICS from the source code\&.
