.TH "fhashtable" 3 "Wed Oct 20 2021" "Version 1.0" "UICS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fhashtable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_value\fP (const char *head, void(*f)(\fBinstHandle\fP *, \fBcmd\fP *))"
.br
.ti -1c
.RI "func_ptr \fBoperator[]\fP (const char *S)"
.br
.ti -1c
.RI "int \fBisInList\fP (std::string)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file fhtable\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UICS from the source code\&.
