.TH "instHandle" 3 "Wed Oct 20 2021" "Version 1.0" "UICS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instHandle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "STATE \fBnextState\fP"
.br
.ti -1c
.RI "STATE \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file insthandle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UICS from the source code\&.
